# Import Libraries

In [1]:
import numpy as np
import pandas as pd

print("Libraries imported successfully")

Libraries imported successfully

# NumPy Basic

## Array Creation

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

## Multi-Dimensional Array

In [3]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]

## Indexing and Slicing

In [4]:
print(arr[0])
print(arr[1:4])

1
[2 3 4]

## Random Numbers

In [5]:
rand_arr = np.random.rand(3,3)
print(rand_arr)

[[0.58106344 0.27741797 0.02740502]
 [0.24459613 0.03157888 0.6665029 ]
 [0.45831421 0.91072482 0.5856648 ]]

## Mathematical Operations

In [6]:
print("Mean:", arr.mean())
print("Sum:", arr.sum())
print("Max:", arr.max())
print("Min:", arr.min())

Mean: 3.0
Sum: 15
Max: 5
Min: 1

# Pandas Basics

## Creating DataFrame

In [7]:
data = {
    "Name": ["Anil", "Rahul", "Priya", "Sneha"],
    "Marks": [85, 90, 88, 92],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi"]
}

df = pd.DataFrame(data)

df

    Name  Marks    City
0   Anil     85   Delhi
1  Rahul     90  Mumbai
2  Priya     88    Pune
3  Sneha     92   Delhi

## Basic Functions

In [8]:
df.head()

    Name  Marks    City
0   Anil     85   Delhi
1  Rahul     90  Mumbai
2  Priya     88    Pune
3  Sneha     92   Delhi

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Marks   4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [10]:
df.describe()

           Marks
count   4.000000
mean   88.750000
std     2.986079
min    85.000000
25%    87.250000
50%    89.000000
75%    90.500000
max    92.000000

## Selecting Columns

In [11]:
df["Name"]

0     Anil
1    Rahul
2    Priya
3    Sneha
Name: Name, dtype: object

In [12]:
df[["Name", "Marks"]]

    Name  Marks
0   Anil     85
1  Rahul     90
2  Priya     88
3  Sneha     92

## Filtering Data

In [13]:
high_marks = df[df["Marks"] > 85]
high_marks

    Name  Marks    City
1  Rahul     90  Mumbai
2  Priya     88    Pune
3  Sneha     92   Delhi

## Adding New Column

In [14]:
df["Bonus"] = df["Marks"] + 5
df

    Name  Marks    City  Bonus
0   Anil     85   Delhi     90
1  Rahul     90  Mumbai     95
2  Priya     88    Pune     93
3  Sneha     92   Delhi     97

## GroupBy Operations

In [15]:
grouped = df.groupby("City")["Marks"].mean()
grouped

City
Delhi     88.5
Mumbai    90.0
Pune      88.0
Name: Marks, dtype: float64

## Sorting Data

In [16]:
sorted_df = df.sort_values(by="Marks", ascending=False)
sorted_df

    Name  Marks    City  Bonus
3  Sneha     92   Delhi     97
1  Rahul     90  Mumbai     95
2  Priya     88    Pune     93
0   Anil     85   Delhi     90

## Handling Missing Values

In [17]:
df.loc[2, "Marks"] = np.nan
df

    Name  Marks    City  Bonus
0   Anil   85.0   Delhi     90
1  Rahul   90.0  Mumbai     95
2  Priya    NaN    Pune     93
3  Sneha   92.0   Delhi     97

### Check missing:

In [19]:
df.isnull().sum()

Name     0
Marks    1
City     0
Bonus    0
dtype: int64

### Fill missing:

In [20]:
df["Marks"].fillna(df["Marks"].mean(), inplace=True)
df

/tmp/ipykernel_55/1415366611.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].mean(), inplace=True)

    Name  Marks    City  Bonus
0   Anil   85.0   Delhi     90
1  Rahul   90.0  Mumbai     95
2  Priya   89.0    Pune     93
3  Sneha   92.0   Delhi     97

## CSV File Operations

### Save CSV

In [27]:
df.to_csv("student_data.csv", index=False)

### Load CSV

In [28]:
new_df = pd.read_csv("student_data.csv")
new_df.head()

    Name  Marks    City  Bonus
0   Anil   85.0   Delhi     90
1  Rahul   90.0  Mumbai     95
2  Priya   89.0    Pune     93
3  Sneha   92.0   Delhi     97

## NumPy vs Pandas Comparison

In [29]:
print("NumPy Array Shape:", arr.shape)
print("Pandas DataFrame Shape:", df.shape)

NumPy Array Shape: (5,)
Pandas DataFrame Shape: (4, 4)

# Conclusion
**In this notebook, NumPy and Pandas libraries were explored for data manipulation and analysis. Various operations such as array creation, indexing, filtering, grouping, and handling missing values were performed. These skills form the foundation for machine learning and data science workflows.**